---
abstract: 'System tables interface via DBI'
author:
  - 'Jens Rehsack <rehsack@cpan.org>, Alexander Breibach <alexander.breibach@googlemail.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBD-Sys
provides:
  Bundle::DBD::Sys:
    file: lib/Bundle/DBD/Sys.pm
    version: 0.01
  DBD::Sys:
    file: lib/DBD/Sys.pm
    version: 0.01
  DBD::Sys::Plugin::Any:
    file: lib/DBD/Sys/Plugin/Any.pm
  DBD::Sys::Plugin::Any::FileSys:
    file: lib/DBD/Sys/Plugin/Any.pm
  DBD::Sys::Plugin::Any::FileSysDf:
    file: lib/DBD/Sys/Plugin/Any.pm
  DBD::Sys::Plugin::Meta:
    file: lib/DBD/Sys/Plugin/Meta.pm
  DBD::Sys::Plugin::Meta::AllTables:
    file: lib/DBD/Sys/Plugin/Meta.pm
  DBD::Sys::Plugin::Unix:
    file: lib/DBD/Sys/Plugin/Unix.pm
  DBD::Sys::Plugin::Unix::GrEnt:
    file: lib/DBD/Sys/Plugin/Unix.pm
  DBD::Sys::Plugin::Unix::NetInterface:
    file: lib/DBD/Sys/Plugin/Unix.pm
  DBD::Sys::Plugin::Unix::Procs:
    file: lib/DBD/Sys/Plugin/Unix.pm
  DBD::Sys::Plugin::Unix::PwEnt:
    file: lib/DBD/Sys/Plugin/Unix.pm
  DBD::Sys::Statement:
    file: lib/DBD/Sys.pm
  DBD::Sys::Table:
    file: lib/DBD/Sys/Table.pm
  DBD::Sys::db:
    file: lib/DBD/Sys.pm
  DBD::Sys::dr:
    file: lib/DBD/Sys.pm
  DBD::Sys::st:
    file: lib/DBD/Sys.pm
recommends:
  DBI: 1.611
  SQL::Statement: 1.27
requires:
  DBI: 1.605
  Module::Pluggable: 3.9
  Params::Util: 1.00
  SQL::Statement: 1.22
  Scalar::Util: 1.00
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
