---
name: DBD-Sys
version: 0.01
author:
  - 'Jens Rehsack <rehsack@cpan.org>, Alexander Breibach <alexander.breibach@googlemail.com>'
abstract: System tables interface via DBI
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 1.41
  Module::Pluggable: 3.9
  Params::Util: 1.00
  SQL::Statement: 1.20
  Scalar::Util: 1.00
recommends:
  Filesys::DfPortable: 0.83
  Proc::ProcessTable: 0.45
  Sys::Filesystem: 1.00
configure_requires:
  Module::Build: 0.35
provides:
  Bundle::DBD::Sys:
    file: lib/Bundle/DBD/Sys.pm
    version: 0.01
  DBD::Sys:
    file: lib/DBD/Sys.pm
    version: 0.01
  DBD::Sys::Plugin::Any:
    file: lib/DBD/Sys/Plugin/Any.pm
  DBD::Sys::Plugin::Any::FileSys:
    file: lib/DBD/Sys/Plugin/Any.pm
  DBD::Sys::Plugin::Any::FileSysDf:
    file: lib/DBD/Sys/Plugin/Any.pm
  DBD::Sys::Plugin::Meta:
    file: lib/DBD/Sys/Plugin/Meta.pm
  DBD::Sys::Plugin::Meta::AllTables:
    file: lib/DBD/Sys/Plugin/Meta.pm
  DBD::Sys::Plugin::Unix:
    file: lib/DBD/Sys/Plugin/Unix.pm
  DBD::Sys::Plugin::Unix::GrEnt:
    file: lib/DBD/Sys/Plugin/Unix.pm
  DBD::Sys::Plugin::Unix::Procs:
    file: lib/DBD/Sys/Plugin/Unix.pm
  DBD::Sys::Plugin::Unix::PwEnt:
    file: lib/DBD/Sys/Plugin/Unix.pm
  DBD::Sys::Statement:
    file: lib/DBD/Sys.pm
  DBD::Sys::Table:
    file: lib/DBD/Sys/Table.pm
  DBD::Sys::db:
    file: lib/DBD/Sys.pm
  DBD::Sys::dr:
    file: lib/DBD/Sys.pm
  DBD::Sys::st:
    file: lib/DBD/Sys.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
